### ISSUE TITLE
Use cases where apko is not recommended?

### ISSUE THREAD

**Issue by shykes** [chainguard-dev/apko#44]
We rely on Alpine images a lot for https://dagger.io (it's our base image of choice). At the moment we have quite a lot of automation built around pulling a base OCI image, then executing `apk`. It seems like perhaps we could (should?) use `apko` instead. Is the goal for apko to be a drop-in replacement for *all* alpine image builds? Or are there cases where it's not the best tool?

Note: at the moment I'm not interested in the "your app artifacts are apk packages" pattern. I just want the best possible way to build an image. Will `apko` make it a requirement to go all in on that pattern, or can I stick to assembling system packages and still be considered a first-class citizen?

**Comment by kaniini** [comment]
`apko` is suitable for building base images where you have all of the artifacts you want to put in that layer already.  If you want to add more stuff outside of APK artifacts, then yes, composing it with other tools (such as `ko` or `docker`) is a supported usecase.  We want to enable people to use the patterns that suit them the best.

**Comment by kaniini** [comment]
I'm planning to do a blog outlining the wider vision over the next week or so, either on the Chainguard blog or my own personal one, which should outline a few envisioned usage scenarios.

Obviously at Chainguard, we're very into the "your app artifacts are also apk packages" pattern because that makes compliance and auditability (e.g. scanning, SBOMs, etc.) really easy, but as I'm sure you're aware, philosophically, it's always been the position of the Alpine community that good ideas and tooling will become dominant without forcing anyone into any specific workflow, and that belief is also reflected at Chainguard :)

**Comment by shykes** [comment]
Yes the pattern is definitely interesting and I agree with your assessment that it will gradually gain ground as a best pratice. It just doesn't coincide with my immediate use case.

**Comment by kaniini** [comment]
Yep, anyway, composing `apko` in pipelines with other tools is fully supported, and encouraged, for example to generate base images for `ko` and `kaniko` to layer things on top.

**Comment by amouat** [comment]
This info was added to the FAQ, so I'm going to close this issue. Please open a new issue if I've missed something.
