### ISSUE TITLE
Is it OK to wrap apko?

### ISSUE THREAD

**Issue by shykes** [chainguard-dev/apko#46]
Is it considered a valid use case to integrate `apko` into a higher-level tool or toolchain? Or is it your preference that end-users always interact with `apko` directly (either in the terminal or by bespoke scripts).

Early on, `docker` wrapped lxc. But we later discovered that the developers of lxc did not consider this a valid use case: it was important to them that lxc never be hidden from the end user. As a result interfaces broke often, unaddressed issues piled up, and generally everyone grew frustrated. Eventually we had to ditch lxc altogether and implement libcontainer, and later runc.

What is your perspective on this? I think both answers are valid, it's just good to know in advance.

Thanks!

**Comment by kaniini** [comment]
We are trying to keep the `apko` CLI stable, but it may break in the future.  In such case, we would try to announce any planned breakage ahead of time in `NEWS.md`.

**Comment by sipsma** [comment]
> We are trying to keep the apko CLI stable

Follow up question, what about importing the Go code here as a library to be used by other tools? Should external users expect any stability in that regard?

To give a little more context, I'm looking into Dagger+apko integration using some new features I recently added to Buildkit (which Dagger is built on top of) that were coincidentally designed to support use cases pretty much exactly like this ([some docs here if interested](https://github.com/moby/buildkit/blob/master/docs/merge%2Bdiff.md#example-use-case-modeling-package-builds-with-mergeopdiffop)).

Dagger/Buildkit already has the machinery for managing layers and exporting container images, it more just needs help with some of the apk-specific stuff such as "turn this list of alpine packages into a DAG including transitive dependencies" and possibly some of the stuff you're doing with the supervision tree. So that makes me think that the apko CLI could end up being too high level.

I guess the possibilities (which aren't mutually exclusive) would be:
1. Shell out to apko
2. Shell out to apk directly (similar to what apko does, would probably end up rewriting a lot of code that's here)
3. Import apko code as a library, use that
4. Import `libapk-go`, which I saw referenced in a comment in the code but didn't find during a brief google

Much more investigation is needed to determine the tradeoffs here of course, so I'm just wondering if any of those options immediately sound like a bad idea that I should rule out or if you have any extra thoughts 🙏

**Comment by kaniini** [comment]
I'm down to merge any refactoring patches you want to do to drive apko programatically as a library, but it's not a direct interest area of mine (as the maintainer of `apko`).

**Comment by sipsma** [comment]
Awesome, appreciate it!

**Comment by amouat** [comment]
I think we can close this, please open a new ticket if there's something that needs done or isn't clear.
