### ISSUE TITLE
SBOMs are missing data about files

### ISSUE THREAD

**Issue by luhring** [chainguard-dev/apko#584]
This appears to be a regression. Before:

```console
$ cosign download sbom --platform linux/arm64 cgr.dev/chainguard/maven:latest-20230131 | jq 'keys | contains(["files"])'
...
true
```

Now:

```console
$ cosign download sbom --platform linux/arm64 cgr.dev/chainguard/maven | jq 'keys | contains(["files"])'
...
false
```

The suspected cause of this behavior is that `apko` is no longer incorporating SBOM data that Melange puts into individual apks at `/var/lib/db/sbom/...`. This would mean that additional data is missing from SBOMs now, beyond just file data.

cc: @rawlingsj

**Comment by deitch** [comment]
I found the issue. We generate the per-arch image [here](https://github.com/chainguard-dev/apko/blob/ac11fae86da15e8288c5e092b4a5217e31e367b7/internal/cli/build.go#L188-L209), saving the results to a layerTarGZ:

```go
			bc.Options.Arch = arch
			bc.Options.WorkDir = wd

			if err := bc.Refresh(); err != nil {
				return fmt.Errorf("failed to update build context for %q: %w", arch, err)
			}

			layerTarGZ, err := bc.BuildLayer()
			if err != nil {
				return fmt.Errorf("failed to build layer image: %w", err)
			}

			imageTars[arch] = layerTarGZ
			img, err := oci.BuildImageFromLayer(
				layerTarGZ, bc.ImageConfiguration, bc.Logger(), bc.Options)
			if err != nil {
				return fmt.Errorf("failed to build OCI image: %w", err)
			}
			imgs[arch] = img
			return nil
```

This is all based around a per-arch `BuildContext` initiated earlier on [here](https://github.com/chainguard-dev/apko/blob/ac11fae86da15e8288c5e092b4a5217e31e367b7/internal/cli/build.go#L178). That `BuildContext` has the `fsys` as a property. Because of all of the issues with local filesystems (case-insensitivity sometimes, permissions, ownership, devices, etc.), a lot of the overrides are in memory.

Once the build is done, we lose the `BuildContext` - and the `fsys` - but we don't care because the build is done and everything is in the layer tarfile, which was our goal.

When we _later_ generate the per-image (and index) SBoM, we do it [here](https://github.com/chainguard-dev/apko/blob/ac11fae86da15e8288c5e092b4a5217e31e367b7/internal/cli/build.go#L218-L238):

```go
	if wantSBOM {
		logrus.Info("Generating arch image SBOMs")
		for arch, img := range imgs {
			// working directory for this architecture
			wd := filepath.Join(workDir, arch.ToAPK())
			bc, err := build.New(wd, opts...)
			if err != nil {
				return err
			}
			bc.Options.WantSBOM = true
			bc.Options.Arch = arch
			bc.Options.TarballPath = imageTars[arch]
			bc.Options.WorkDir = wd
			bc.Options.SBOMFormats = formats
			bc.Options.SBOMPath = sbomPath

			if err := bc.GenerateImageSBOM(arch, img); err != nil {
				return fmt.Errorf("generating sbom for %s: %w", arch, err)
			}
		}
	}
```

Notice that we create a _new_ `BuildContext`, and therefore a new `fsys` based around the same working directory (which happens to still exist, but need not). Since it is new, all of the in-memory information is gone, so it cannot find some things it needs.

We have two options.

* Keep the fsys reference (or even the `BuildContext` itself) and reuse it when generating the SBoM
* Read it all from the tarfile

I suspect the more robust solution is the tarfile, but the easier one Is holding onto the `BuildContext`. So I will try that first.
