### ISSUE TITLE
Copy Annotations into config.json (Docker Labels)

### ISSUE THREAD

**Issue by amouat** [chainguard-dev/apko#692]
Apko currently supports adding annotations as per the OCI Image spec: https://github.com/opencontainers/image-spec/blob/main/annotations.md

Docker's support for annotations seems a bit mixed, and in particular `docker inspect` will not display annotations. For this reason, it might be worth adding annotations into the [config](https://github.com/opencontainers/image-spec/blob/main/config.md), which will get surfaced in `docker inspect` and easily found/searched/scripted etc.

**Comment by mritunjaysharma394** [comment]
Oh that makes sense, thanks a bunch @amouat,  I think so that more or less I have understood the assignment here: update Labels which are a map so annotations can be hopefully easily added here but I suppose we already have [Annotations in Manifest struct](https://github.com/google/go-containerregistry/blob/main/pkg/v1/manifest.go#L30) so that should be handleable too? 

If that sounds okay, maybe I can try to get my hands dirty and create a PR/Draft PR to implement this? Thanks again :pray:

**Comment by amouat** [comment]
That would be great @mritunjaysharma394! However, I would like @kaniini or someone to verify that we do want this functionality first. 

Assuming we do, it's hopefully just a case of copying the annotations struct into the labels struct for the config.
