### ISSUE TITLE
OCI Layout support

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/apko#74]
apko should support `--oci-layout-path`, like `ko` and Kaniko, to also push OCI image/index contents to a local path. This hooks into other workflows that can (for example) do some scan locally before pushing in a subsequent step. Having a local layout option means there can be a `--push` (default true) flag, since writing the layout might mean you don't want to push.

See https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/layout#Write

**Comment by dlorenc** [comment]
whoops, i was playing with some github project automation and screwed something up.

**Comment by vito** [comment]
Would very much like this! There are certain scenarios where passing around a layout directory rather than a tarball makes a huge performance difference: https://github.com/dagger/dagger/pull/5363

I tried passing `/dev/stdout` as the tarball path and piping to `tar -xf -` to avoid hitting the disk twice, but the resulting directory isn't actually a valid OCI layout because all the blobs are at the root level instead of under `blobs/`. I suppose that means the output tarball isn't actually valid OCI either.

If I find some time I'll try to put a PR together. Seems like it shouldn't be difficult.
